# Tell Travis what to do
# https://travis-ci.com/nedbat/cog

dist: xenial
language: python

cache: pip
python:
  - '2.7'
  - '3.5'
  - '3.6'
  - '3.7'
  - 'pypy2.7-6.0'
  - 'pypy3.5-6.0'

install:
  - pip install -r requirements.pip
  - pip freeze

script:
  - tox
